*** Starting uWSGI 2.0.18 (64bit) on [Fri May 29 10:46:58 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
writing pidfile to /root/mshd/uwsgi.pid
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5640f3164280
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5640f3164280 pid: 1521 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1521)
spawned uWSGI worker 1 (pid: 1524, cores: 1)
Fri May 29 02:48:19 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 29 11:02:09 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
writing pidfile to /root/mshd/uwsgi.pid
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55ddeef61280
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55ddeef61280 pid: 2148 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2148)
spawned uWSGI worker 1 (pid: 2151, cores: 1)
Internal Server Error: /admin/djcelery/taskstate/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'my_mshd.djcelery_workerstate' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 741, in get_changelist_instance
    sortable_by,
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/djcelery/admin.py", line 49, in __init__
    super(MonitorList, self).__init__(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 97, in __init__
    self.queryset = self.get_queryset(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 423, in get_queryset
    filters_use_distinct) = self.get_filters(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 151, in get_filters
    self.model, self.model_admin, field_path=field_path,
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 159, in create
    return list_filter_class(field, request, params, model, model_admin, field_path=field_path)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 170, in __init__
    self.lookup_choices = self.field_choices(field, request, model_admin)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 207, in field_choices
    return field.get_choices(include_blank=False, ordering=ordering)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 865, in get_choices
    (choice_func(x), str(x)) for x in qs
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_mshd.djcelery_workerstate' doesn't exist")
Internal Server Error: /admin/djcelery/crontabschedule/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'my_mshd.djcelery_crontabschedule' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 741, in get_changelist_instance
    sortable_by,
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 98, in __init__
    self.get_results(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 226, in get_results
    result_count = paginator.count
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/paginator.py", line 91, in count
    return c()
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 397, in count
    return self.query.get_count(using=self.db)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 517, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 502, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_mshd.djcelery_crontabschedule' doesn't exist")
Internal Server Error: /admin/djcelery/intervalschedule/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'my_mshd.djcelery_intervalschedule' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 741, in get_changelist_instance
    sortable_by,
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 98, in __init__
    self.get_results(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 226, in get_results
    result_count = paginator.count
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/paginator.py", line 91, in count
    return c()
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 397, in count
    return self.query.get_count(using=self.db)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 517, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 502, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_mshd.djcelery_intervalschedule' doesn't exist")
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /index.php
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
...gracefully killing workers...
Gracefully killing worker 1 (pid: 2151)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 29 03:43:28 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55f8e09f8a70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55f8e09f8a70 pid: 2148 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 2148)
spawned uWSGI worker 1 (pid: 3232, cores: 1)
Internal Server Error: /admin/djcelery/crontabschedule/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'my_mshd.djcelery_crontabschedule' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 741, in get_changelist_instance
    sortable_by,
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 98, in __init__
    self.get_results(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 226, in get_results
    result_count = paginator.count
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/paginator.py", line 91, in count
    return c()
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 397, in count
    return self.query.get_count(using=self.db)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 517, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 502, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_mshd.djcelery_crontabschedule' doesn't exist")
Internal Server Error: /admin/djcelery/periodictask/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'my_mshd.djcelery_periodictask' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/djcelery/admin.py", line 376, in changelist_view
    extra_context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/options.py", line 741, in get_changelist_instance
    sortable_by,
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 98, in __init__
    self.get_results(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/contrib/admin/views/main.py", line 226, in get_results
    result_count = paginator.count
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/paginator.py", line 91, in count
    return c()
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 397, in count
    return self.query.get_count(using=self.db)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 517, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/query.py", line 502, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'my_mshd.djcelery_periodictask' doesn't exist")
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3232)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 29 11:58:01 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x561536722c10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561536722c10 pid: 2148 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 2148)
spawned uWSGI worker 1 (pid: 3776, cores: 1)
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /0bef
Not Found: /operator/basic.shtml
Not Found: /doLogin
Not Found: /doLogin
Not Found: /
Not Found: /favicon.ico
Not Found: /
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3776)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Fri May 29 15:23:03 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x560d590fcc10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x560d590fcc10 pid: 2148 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 2148)
spawned uWSGI worker 1 (pid: 10574, cores: 1)
Not Found: /:5555
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /hudson
Not Found: /phpmyadmin
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /setup.cgi
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /Lists/admin.php
Not Found: /admin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /cache/global/img/gs.gif
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /hudson
Not Found: /
Not Found: /
Not Found: /
Not Found: /%{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#res=@org.apache.struts2.ServletActionContext@getResponse()).(#res.addHeader('eresult','struts2_security_check'))}/login.action
Not Found: /login.action
Not Found: /login.action
Not Found: /login.action
Not Found: /login.action
Not Found: /login.action
Not Found: /login.action
Not Found: /login.action
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /favicon.ico
Not Found: /cgi-bin/mainfunction.cgi
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /nmaplowercheck1590951137
Not Found: /sdk
Not Found: /evox/about
Not Found: /
Not Found: /HNAP1
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /cgi-bin/mainfunction.cgi
Not Found: /
Not Found: /portal/redlion
Not Found: /
Not Found: /adv,/cgi-bin/weblogin.cgi
Not Found: /favicon.ico
Not Found: /manager/text/list
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.htm
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /favicon.ico
...gracefully killing workers...
Gracefully killing worker 1 (pid: 10574)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun  1 11:28:35 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5584f9199ab0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5584f9199ab0 pid: 2148 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 2148)
spawned uWSGI worker 1 (pid: 12040, cores: 1)
Mon Jun  1 11:34:45 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun  1 19:40:48 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
writing pidfile to /root/mshd/uwsgi.pid
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x556828ef2280
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x556828ef2280 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 12606, cores: 1)
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /404/search_children.js
Not Found: /hudson
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /erm/help/how_to_getstarted.html
Not Found: /cn.gzjs
Not Found: /etms/assets/bundle/commons.js
Not Found: /index.html
Not Found: /EIMSII/assets/bundle/commons.js
Not Found: /eims3/assets/bundle/commons.js
Not Found: /goip/cron.htm
Not Found: /chs/js/lang_zh_tw.js
Not Found: /smb_scheduler/cdr.htm
Not Found: /
Not Found: /vicidial/admin.php
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /Telerik.Web.UI.WebResource.axd
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /robots.txt
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /azenv.php
Not Found: /favicon.ico
Not Found: /
Not Found: /shell
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /portal/redlion
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /robots.txt
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /assets/logs/fullz.txt
Not Found: /
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /hudson
Not Found: /
Not Found: /adv,/cgi-bin/weblogin.cgi
Not Found: /WEB_VMS/LEVEL15/
Not Found: /cache/global/img/gs.gif
Not Found: /assets/logs/fullz.txt
Not Found: /
Not Found: /
Not Found: /manager/html
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /_async/AsyncResponseService
Not Found: /wls-wsat/CoordinatorPortType11
Not Found: /666666/
Not Found: /
Not Found: /phpmyadmin/
Not Found: /pmd/
Not Found: /mysqladmin/
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /phpmyadmin/
Not Found: /pmd/
Not Found: /mysqladmin/
Not Found: /phpmyadmin/
Not Found: /pmd/
Not Found: /mysqladmin/
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /robots.txt
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /phpmyadmin/
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /api/jsonws/invoke
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /phpmyadmin/index.php
Not Found: /phpMyadmin/index.php
Not Found: /phpMyAdmin/index.php
Not Found: /phpMyAdmin/index.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /index.html
Not Found: /smb_scheduler/cdr.htm
Not Found: /goip/cron.htm
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /phpmyadmin/index.php
Not Found: /phpMyadmin/index.php
Not Found: /phpMyAdmin/index.php
Not Found: /phpMyAdmin/index.php
Not Found: /
Not Found: /robots.txt
Not Found: /adv,/cgi-bin/weblogin.cgi
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /index.php
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /hudson
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /echo.php
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /5555
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /phpMyAdmin4.8.5/js/server_status_monitor.js
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /portal/redlion
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /azenv.php
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /GponForm/diag_Form
Not Found: /index.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /WEB_VMS/LEVEL15/
Not Found: /
Not Found: /
Not Found: /HNAP1/
Not Found: /
Not Found: /hudson
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /cache/global/img/gs.gif
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /HNAP1/
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /echo.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /portal/redlion
Not Found: /
Not Found: /
Not Found: /boaform/admin/formLogin
Not Found: /cgi-bin/mainfunction.cgi
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /vicidial/admin.php
Not Found: /
Not Found: /index.html
Not Found: /smb_scheduler/cdr.htm
Not Found: /goip/cron.htm
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /hudson
...gracefully killing workers...
Gracefully killing worker 1 (pid: 12606)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun  8 11:57:55 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5593e1108a70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5593e1108a70 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 6927, cores: 1)
Internal Server Error: /index/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mshd/urls.py", line 18, in <module>
    from DataStorage.views import  *
  File "/root/mshd/DataStorage/views.py", line 4, in <module>
    from django.shortcuts import render_to_response
ImportError: cannot import name 'render_to_response' from 'django.shortcuts' (/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/shortcuts.py)
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    if self.should_redirect_with_slash(request):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/middleware/common.py", line 71, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/base.py", line 154, in is_valid_path
    resolve(path, urlconf)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/base.py", line 25, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./mshd/urls.py", line 18, in <module>
    from DataStorage.views import  *
  File "/root/mshd/DataStorage/views.py", line 4, in <module>
    from django.shortcuts import render_to_response
ImportError: cannot import name 'render_to_response' from 'django.shortcuts' (/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/shortcuts.py)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6927)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun  8 12:01:02 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a54a956a70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55a54a956a70 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 7031, cores: 1)
Not Found: /favicon.ico
Internal Server Error: /DataStorage/showsentData/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'status' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/mshd/DataStorage/views.py", line 335, in showsentData
    models.DisasterRequest.objects.filter(status='1').update(status='已发送')
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/query.py", line 752, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1499, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'status' at row 1")
...gracefully killing workers...
Gracefully killing worker 1 (pid: 7031)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jun  8 12:04:06 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x562b5d28aa70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x562b5d28aa70 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 7114, cores: 1)
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /adv,/cgi-bin/weblogin.cgi
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /phpmyadmin
Not Found: /
Not Found: /
Not Found: /
Not Found: /w00tw00t.at.blackhats.romanian.anti-sec:)
Not Found: /phpMyAdmin/scripts/setup.php
Not Found: /phpmyadmin/scripts/setup.php
Not Found: /pma/scripts/setup.php
Not Found: /myadmin/scripts/setup.php
Not Found: /MyAdmin/scripts/setup.php
Not Found: /muieblackcat
Not Found: /phpMyAdmin/scripts/setup.php
Not Found: /phpmyadmin/scripts/setup.php
Not Found: /pma/scripts/setup.php
Not Found: /myadmin/scripts/setup.php
Not Found: /MyAdmin/scripts/setup.php
Not Found: /PhpMyAdmin/scripts/setup.php
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /cache/global/img/gs.gif
Not Found: /phpmyadmin/
Not Found: /pmd/
Not Found: /mysqladmin/
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Internal Server Error: /upload/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/mshd/upload/views.py", line 22, in upload
    files = os.listdir('D:/upload')
FileNotFoundError: [Errno 2] No such file or directory: 'D:/upload'
Not Found: /favicon.ico
Not Found: /
...gracefully killing workers...
Gracefully killing worker 1 (pid: 7114)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Jun  9 04:40:27 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55e45a616a70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55e45a616a70 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 2625, cores: 1)
Not Found: /favicon.ico
...gracefully killing workers...
Gracefully killing worker 1 (pid: 2625)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Jun  9 04:43:18 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55b7ad530a70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55b7ad530a70 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 2732, cores: 1)
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cloud-app/include/css/uncall.css
Not Found: /app/common.js
Not Found: /recordings/misc/recording_popup.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
...gracefully killing workers...
Gracefully killing worker 1 (pid: 2732)...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mshd
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/MSHD/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Jun  9 12:32:35 2020] ***
compiled with version: 7.4.0 on 08 May 2020 07:44:33
os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
nodename: Jonathan
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mshd
detected binary path: /root/.virtualenvs/MSHD/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/mshd
your processes number limit is 7796
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x56346612ea70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56346612ea70 pid: 12603 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12603)
spawned uWSGI worker 1 (pid: 17567, cores: 1)
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /azenv.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /t
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /solr/admin/info/system
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /TP/public/index.php
Not Found: /TP/index.php
Not Found: /thinkphp/html/public/index.php
Not Found: /html/public/index.php
Not Found: /public/index.php
Not Found: /TP/html/public/index.php
Not Found: /elrekt.php
Not Found: /index.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /api/jsonws/invoke
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /hudson
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /
Not Found: /muieblackcat
Not Found: /phpMyAdmin/scripts/setup.php
Not Found: /phpmyadmin/scripts/setup.php
Not Found: /pma/scripts/setup.php
Not Found: /myadmin/scripts/setup.php
Not Found: /MyAdmin/scripts/setup.php
Not Found: /PhpMyAdmin/scripts/setup.php
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /adv,/cgi-bin/weblogin.cgi
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /manager/html
Not Found: /
Not Found: /0bef
Not Found: /.git/config
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /
Not Found: /index.php
Not Found: /phpmyadmin/index.php
Not Found: /
Not Found: /.git/config
Not Found: /
Not Found: /
Not Found: /cache/global/img/gs.gif
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Internal Server Error: /upload/
Traceback (most recent call last):
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/MSHD/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/mshd/upload/views.py", line 22, in upload
    files = os.listdir('D:/upload')
FileNotFoundError: [Errno 2] No such file or directory: 'D:/upload'
Not Found: /favicon.ico
Not Found: /
Not Found: /
Not Found: /
Not Found: /echo.php
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
